build.gradle.kts, src/main/kotlin/goodspace/teaming/TeamingApplication.kt, src/main/kotlin/goodspace/teaming/global/entity/BaseEntity.kt, src/main/kotlin/goodspace/teaming/global/entity/file/AttachedFile.kt, src/main/kotlin/goodspace/teaming/global/entity/file/File.kt, src/main/kotlin/goodspace/teaming/global/entity/room/Message.kt, src/main/kotlin/goodspace/teaming/global/entity/room/Room.kt, src/main/kotlin/goodspace/teaming/global/entity/room/UserRoom.kt, src/main/kotlin/goodspace/teaming/global/entity/user/User.kt, src/main/kotlin/goodspace/teaming/global/entity/user/UserRole.kt, src/main/kotlin/goodspace/teaming/global/security/RefreshToken.kt, src/main/kotlin/goodspace/teaming/global/security/SecurityConfig.kt, src/main/kotlin/goodspace/teaming/global/swagger/SwaggerConfig.kt
`SwaggerConfig`를 추가했습니다.
Swagger를 위해, `SecurityConfig`에 비인증 엔드포인트를 추가했습니다.
`BaseEntity`가 잘못된 패키지 경로를 지닌 문제를 수정했습니다.
어플리케이션에 `JpaAuditing`이 허용되지 않던 문제를 수정했습니다.
#8
=> [feat/#8] Swagger 설정파일 추가

src/main/kotlin/goodspace/teaming/chat/controller/ChatRestController.kt, src/main/kotlin/goodspace/teaming/chat/domain/mapper/RoomSearchMapper.kt, src/main/kotlin/goodspace/teaming/chat/domain/mapper/RoomTypeMapper.kt, src/main/kotlin/goodspace/teaming/chat/dto/RoomSearchResponseDto.kt, src/main/kotlin/goodspace/teaming/chat/dto/RoomTypeResponseDto.kt, src/main/kotlin/goodspace/teaming/chat/service/RoomService.kt, src/main/kotlin/goodspace/teaming/chat/service/RoomServiceImpl.kt, src/main/kotlin/goodspace/teaming/global/entity/room/Room.kt, src/main/kotlin/goodspace/teaming/global/entity/room/RoomType.kt, src/test/kotlin/goodspace/teaming/chat/domain/mapper/RoomInfoMapperTest.kt, src/test/kotlin/goodspace/teaming/chat/domain/mapper/RoomSearchMapperTest.kt, src/test/kotlin/goodspace/teaming/chat/domain/mapper/RoomTypeMapperTest.kt, src/test/kotlin/goodspace/teaming/chat/service/RoomServiceTest.kt
초대코드를 통해 티밍룸을 검색하는 API를 구현했습니다.
#19
=> [feat/#19] 티밍룸 검색 API 구현

src/main/kotlin/goodspace/teaming/global/entity/user/User.kt, src/main/kotlin/goodspace/teaming/init/AdminUserInitializer.kt
애플리케이션 시작 시점에 2개의 테스트 관리자 계정을 생성하도록 구현했습니다.
#26
=> [feat/#26] 테스트용 관리자 계정 생성

src/main/kotlin/goodspace/teaming/global/repository/RoomRepository.kt, src/main/kotlin/goodspace/teaming/global/security/SecurityConfig.kt, src/main/kotlin/goodspace/teaming/landing/controller/LandingPageController.kt, src/main/kotlin/goodspace/teaming/landing/dto/StatisticResponseDto.kt, src/main/kotlin/goodspace/teaming/landing/service/LandingPageService.kt, src/main/kotlin/goodspace/teaming/landing/service/LandingPageServiceImpl.kt
랜딩 페이지를 위해 서비스 통계 API를 구현했습니다.
#32
=> [chore/#32] 랜딩 페이지용 통계 API 구현

src/main/kotlin/goodspace/teaming/global/exception/GlobalExceptionHandler.kt
예외가 클라이언트에게 일관된 상태 코드를 반환하도록 전역 예외 핸들러를 구현했습니다.
#34
=> [chore/#34] 전역 예외 핸들러 구현

src/main/kotlin/goodspace/teaming/assignment/service/AssignmentServiceImpl.kt, src/main/kotlin/goodspace/teaming/global/entity/aissgnment/Assignment.kt, src/main/kotlin/goodspace/teaming/global/entity/room/Room.kt, src/test/kotlin/goodspace/teaming/assignment/service/AssignmentServiceTest.kt, src/test/kotlin/goodspace/teaming/fixture/AssignedMemberConstants.kt, src/test/kotlin/goodspace/teaming/fixture/AssignmentConstants.kt, src/test/kotlin/goodspace/teaming/fixture/RoomConstants.kt, src/test/kotlin/goodspace/teaming/fixture/UserConstantFixture.kt, src/test/kotlin/goodspace/teaming/fixture/UserRoomConstants.kt, src/test/kotlin/goodspace/teaming/landing/service/LandingPageServiceTest.kt
이전에 마무리하지 못했던 테스트 코드를 모두 작성했습니다.
`AssignmentService` 로직에 존재하던 허점을 보완했습니다.
#21 
#32 
#36
=> [chore/#36] 누락된 테스트 코드 구현

src/main/kotlin/goodspace/teaming/assignment/controller/AssignmentController.kt, src/main/kotlin/goodspace/teaming/assignment/service/AssignmentService.kt, src/main/kotlin/goodspace/teaming/assignment/service/AssignmentServiceImpl.kt, src/main/kotlin/goodspace/teaming/global/entity/aissgnment/AssignmentStatus.kt, src/main/kotlin/goodspace/teaming/global/repository/UserRoomRepository.kt, src/test/kotlin/goodspace/teaming/assignment/service/AssignmentServiceTest.kt
아직 완수되지 않은 과제를 취소할 수 있는 API를 구현했습니다.
#41 
API의 세부 내용은 이슈를 참고하시길 바랍니다.
=> [chore/#41] 과제 취소 API 구현

src/main/kotlin/goodspace/teaming/global/security/SecurityConfig.kt
회원 가입 엔드포인트에 대해 JWT 인증을 수행하지 않도록 수정했습니다.
#5
=> [fix/#5] 회원 가입 엔드포인트가 JWT 인증 경로에 포함된 문제 수정

src/main/kotlin/goodspace/teaming/authorization/dto/GoogleAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/KakaoAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/NaverAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/GoogleAuthService.kt
=> [modify] delete jsonProperty in socialsAccessTokenDtos

src/main/kotlin/goodspace/teaming/authorization/dto/KakaoUserInfoResponseDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/NaverUserInfoResponseDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/KakaoAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/NaverAuthService.kt
=> [modify] add ? operator in kakaoUserInfo, modify url in naverAuthService

src/main/kotlin/goodspace/teaming/authorization/dto/NaverUserInfoResponseDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/NaverAuthService.kt
=> [modify] not null handling in naverAuthService

src/main/kotlin/goodspace/teaming/authorization/dto/NaverUserInfoResponseDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/NaverAuthService.kt
=> [modify] modify field in NaverUserInfo

src/main/kotlin/goodspace/teaming/authorization/controller/AppAuthController.kt, src/main/kotlin/goodspace/teaming/authorization/dto/AppOauthRequestDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/GoogleAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/KakaoAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/NaverAuthService.kt
=> [modify] delete scope in kakaoToken login

src/main/kotlin/goodspace/teaming/authorization/dto/GoogleAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/KakaoAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/NaverAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/GoogleAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/KakaoAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/NaverAuthService.kt
=> [modify] add json snakeCase

src/main/kotlin/goodspace/teaming/authorization/dto/GoogleAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/KakaoAccessTokenDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/NaverAccessTokenDto.kt
=> [modify]SerializeName

src/main/kotlin/goodspace/teaming/authorization/service/GoogleAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/NaverAuthService.kt
=> [modify] delete scope in google, naver

src/main/kotlin/goodspace/teaming/init/AdminUserInitializer.kt
테스트 유저의 비밀번호에 암호화가 적용되어 있지 않은 문제를 해결했습니다.
#26
=> [fix/#26] 테스트 유저의 비밀번호도 암호화 적용

src/main/kotlin/goodspace/teaming/authorization/service/TeamingAuthService.kt, src/main/kotlin/goodspace/teaming/global/repository/UserRepository.kt, src/test/kotlin/goodspace/teaming/authorization/service/TeamingAuthServiceTest.kt
=> [fix/#5] 비밀번호 검증 로직 수정

src/main/kotlin/goodspace/teaming/authorization/controller/AppAuthController.kt, src/main/kotlin/goodspace/teaming/authorization/dto/AppleIdTokenPayloadDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/AppleOauthRequestDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/AppleSignInRequestDto.kt, src/main/kotlin/goodspace/teaming/authorization/dto/AppleTokenResponseDto.kt, src/main/kotlin/goodspace/teaming/authorization/request/SignUpRequestDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/AppleAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/GoogleAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/KakaoAuthService.kt, src/main/kotlin/goodspace/teaming/authorization/service/NaverAuthService.kt, src/main/kotlin/goodspace/teaming/global/entity/user/OAuthUser.kt
애플 회원가입/로그인을 구현했습니다.
사용자 아바타 이미지 등록 방식에 문제가 있어 임시로 주석처리 했습니다.
#66
=> [feature/#66] 애플 OAuth 구현

src/main/kotlin/goodspace/teaming/authorization/dto/AppleOauthRequestDto.kt, src/main/kotlin/goodspace/teaming/authorization/service/AppleAuthService.kt
=> [fix/#66] Apple Oauth 요청 파라미터에 `codeVerifier` 추가

src/main/kotlin/goodspace/teaming/authorization/service/AppleAuthService.kt
=> [chore/#66] Expo 테스트용 AUD 허용

src/main/kotlin/goodspace/teaming/payment/controller/PaymentController.kt
=> [feat] test for app

src/main/kotlin/goodspace/teaming/assignment/service/AssignmentServiceImpl.kt
시간 비교 로직이 반대로 되어있는 문제를 해결했습니다.
#96
=> [chore/#96] 시간 비교 로직 오류 해결

src/main/kotlin/goodspace/teaming/punishment/scheduler/PunishmentScheduler.kt
=> [feat] handle transaction

src/main/kotlin/goodspace/teaming/admin/controller/GifticonController.kt, src/main/kotlin/goodspace/teaming/gifticon/repository/GifticonRepository.kt, src/main/kotlin/goodspace/teaming/gifticon/service/GifticonService.kt, src/main/kotlin/goodspace/teaming/global/repository/UserRepository.kt
=> [modify] getifticon

src/main/kotlin/goodspace/teaming/chat/domain/mapper/RoomInfoMapper.kt, src/test/kotlin/goodspace/teaming/assignment/service/AssignmentServiceTest.kt, src/test/kotlin/goodspace/teaming/chat/domain/mapper/RoomInfoMapperTest.kt, src/test/kotlin/goodspace/teaming/chat/domain/mapper/RoomMapperTest.kt, src/test/kotlin/goodspace/teaming/chat/domain/mapper/RoomMemberMapperTest.kt, src/test/kotlin/goodspace/teaming/chat/domain/mapper/RoomSearchMapperTest.kt, src/test/kotlin/goodspace/teaming/chat/service/RoomServiceTest.kt, src/test/kotlin/goodspace/teaming/fixture/MessageConstants.kt, src/test/kotlin/goodspace/teaming/util/CreateUtil.kt
배포 환경에 수정사항을 빠르게 반영하기 위해 수정하지 못했던 테스트 코드를 지금 수정했습니다.
#15
=> [fix/#15] 비즈니스 로직 수정을 테스트에 반영

src/main/kotlin/goodspace/teaming/file/dto/AvatarUploadCompleteRequestDto.kt, src/main/kotlin/goodspace/teaming/file/dto/AvatarUploadIntentRequestDto.kt
=> [fix/#124] 누락된 클래스 변경 추가

src/main/kotlin/goodspace/teaming/payment/controller/PaymentController.kt, src/main/kotlin/goodspace/teaming/payment/service/PaymentService.kt
=> [modify] payment logic

src/main/kotlin/goodspace/teaming/payment/controller/PaymentController.kt
=> [modify] payment returnUrl

src/main/kotlin/goodspace/teaming/chat/event/MemberEnteredEvent.kt, src/main/kotlin/goodspace/teaming/chat/event/MemberEnteredEventHandler.kt, src/main/kotlin/goodspace/teaming/chat/service/RoomServiceImpl.kt
방에 새로운 인원이 입장할 때 웹소캣으로 데이터를 전달합니다.
#140
=> [feat/#140] 방 입장 이벤트 발행

src/main/kotlin/goodspace/teaming/chat/service/RoomServiceImpl.kt, src/main/kotlin/goodspace/teaming/global/entity/room/Room.kt
=> [fix] 티밍룸 API 로직 오류 해결

src/main/kotlin/goodspace/teaming/payment/controller/PaymentController.kt
=>  fix RequestParam -> RequestBody

src/main/kotlin/goodspace/teaming/payment/controller/PaymentController.kt
=> fix Long to String
